[package]
name = "donka-release"
description = "Releases, environments, Runtime tokens and deployments of a project"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
donka-audit = { workspace = true }
donka-db = { workspace = true }
donka-decision = { workspace = true }
donka-mail = { workspace = true }
donka-project = { workspace = true }
donka-shared = { workspace = true }
donka-storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zip = { workspace = true }

[lints]
workspace = true
