/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user. */
    get: operations['me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emails a one-time link to choose a new password. Answers the same whether or
     *     not the address has an account, so it cannot be used to find accounts.
     */
    post: operations['password_reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sets a password from a one-time setup link. Ends the user's other sessions. */
    post: operations['password_setup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in and sets the httpOnly session cookie. */
    post: operations['sign_in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session on the server and clears the cookie. */
    post: operations['sign_out'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness: answers as long as the process serves requests. Does not touch the database. */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness: the service can handle requests that need the database. */
    get: operations['ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/simulate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['simulate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invites a person by email (administrators only). Inviting someone who has not
     *     accepted yet sends a new link and revokes the previous one.
     */
    post: operations['invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The version of Studio that is running. Needs no session, like health. */
    get: operations['version'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorBody: {
      /** @description Stable, machine-readable code, e.g. `DECISION_NOT_FOUND`. */
      code: string;
      /** @description Engine error document (failing node and reason) for evaluation failures. */
      details?: unknown;
      fields?: {
        [key: string]: string;
      } | null;
      /** @description Safe to show to a person. */
      message: string;
      /** @description Same value as the `x-request-id` response header; quote it when reporting a problem. */
      requestId: string;
    };
    InvitationRequest: {
      email: string;
      isAdmin?: boolean;
      locale?: null | components['schemas']['Locale'];
    };
    /**
     * @description Language of a user's emails and screens.
     * @enum {string}
     */
    Locale: 'en' | 'fr';
    PasswordResetRequest: {
      email: string;
    };
    PasswordSetupRequest: {
      password: string;
      /** @description The token from the password-setup link. */
      token: string;
    };
    SignInRequest: {
      email: string;
      password: string;
    };
    /**
     * @description Design-time evaluation from the editor. The editor sends the whole draft
     *     project so sub-decision references resolve exactly as they will in a release.
     */
    SimulateRequest: {
      /** @description Input passed to the decision. */
      context?: Record<string, never>;
      /** @description Every decision of the project (JDM documents), keyed as graphs reference them. */
      decisions: Record<string, never>;
      /** @description The decision to evaluate. */
      key: string;
    };
    SimulateResponse: {
      /** @description Engine evaluation time, e.g. `412.5µs`. */
      performance: string;
      result: Record<string, never>;
      /** @description Per-node trace: inputs, outputs and timing of each node. */
      trace: Record<string, never>;
    };
    UserResponse: {
      email: string;
      /** Format: uuid */
      id: string;
      isAdmin: boolean;
      locale: components['schemas']['Locale'];
    };
    VersionResponse: {
      /**
       * @description Release version baked in at build time, or `unknown` for a local build.
       * @example 1.4.0
       */
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description If the address has an account, a reset link is on its way */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not an email address (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_setup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordSetupRequest'];
      };
    };
    responses: {
      /** @description Password set; sign in with it */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Link invalid, used or expired (INVALID_SETUP_LINK), or password too short or too long (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_in: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest'];
      };
    };
    responses: {
      /** @description Signed in; the session cookie is set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Email or password is incorrect, or the account is locked (INVALID_CREDENTIALS) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Missing CSRF header (CSRF_REQUIRED) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_out: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The service is running */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ok */
          'text/plain': string;
        };
      };
    };
  };
  ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ready */
          'text/plain': string;
        };
      };
      /** @description The database is not reachable (DATABASE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  simulate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SimulateRequest'];
      };
    };
    responses: {
      /** @description Result and per-node trace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimulateResponse'];
        };
      };
      /** @description Malformed request body (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description No decision with that key (DECISION_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Invalid decision model (INVALID_DECISION) or evaluation error (EVALUATION_FAILED) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationRequest'];
      };
    };
    responses: {
      /** @description Account created; the invitation email is on its way */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid email (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description The person already has an account (EMAIL_TAKEN) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
}
