/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user. */
    get: operations['me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emails a one-time link to choose a new password. Answers the same whether or
     *     not the address has an account, so it cannot be used to find accounts.
     */
    post: operations['password_reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sets a password from a one-time setup link. Ends the user's other sessions. */
    post: operations['password_setup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in and sets the httpOnly session cookie. */
    post: operations['sign_in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session on the server and clears the cookie. */
    post: operations['sign_out'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness: answers as long as the process serves requests. Does not touch the database. */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects the signed-in user is a member of, by name. */
    get: operations['list'];
    put?: never;
    /** Creates a project (administrators only). The creator becomes its owner. */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/by-key/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A project the signed-in user is a member of, found by its key: the web app
     *     addresses projects by key so its links stay short and readable.
     */
    get: operations['get_by_key'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A project the signed-in user is a member of. */
    get: operations['get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Renames the project or changes its description (owners). The key never changes. */
    patch: operations['update'];
    trace?: never;
  };
  '/projects/{project_id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archives the project: read-only and hidden from the default list (owners). */
    post: operations['archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The project's audit log, newest first (owners). */
    get: operations['list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/audit/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The project's audit log as CSV, with the same filters (owners). At most
     *     50,000 rows; narrow the dates for more.
     */
    get: operations['export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The project's decisions, by key (any member). */
    get: operations['list'];
    put?: never;
    /** A new decision, empty unless content is given (editors and owners). */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One decision with its draft (any member). */
    get: operations['get'];
    /**
     * Saves the draft (editors and owners). Send the revision the draft was loaded
     *     at: when someone saved since, the answer is `409 DECISION_CONFLICT` with who
     *     and when in `details`, and nothing is overwritten.
     */
    put: operations['save'];
    post?: never;
    /**
     * Deletes a decision (editors and owners): it leaves the project and its key
     *     is free again; its versions stay in the history.
     */
    delete: operations['delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}/simulate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Evaluates this decision with every other decision of the project, as a
     *     release would, and returns the result with a per-node trace (any member:
     *     viewers simulate too). Nothing is saved.
     */
    post: operations['simulate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The decision's versions, newest first (any member). */
    get: operations['list'];
    put?: never;
    /** Saves the draft as the next version (editors and owners). */
    post: operations['save'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}/versions/{number}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One version with its content, to compare or restore (any member). */
    get: operations['get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}/versions/{number}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restores a version (editors and owners): its content becomes the draft and a
     *     new version; the history only grows.
     */
    post: operations['restore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/decisions/{decision_id}/versions/{number}/test-results': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** How every scenario of the project went when this version was saved (any member). */
    get: operations['test_results'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Members of the project, owners first, then by email (any member). */
    get: operations['members'];
    put?: never;
    /** Adds an existing Studio user to the project (owners). */
    post: operations['add_member'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Removes a member; the last owner cannot be removed (owners). */
    delete: operations['remove_member'];
    options?: never;
    head?: never;
    /** Changes a member's role; a project always keeps an owner (owners). */
    patch: operations['change_role'];
    trace?: never;
  };
  '/projects/{project_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restores an archived project (owners). */
    post: operations['restore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/test-scenarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The project's scenarios, by decision and name (any member). */
    get: operations['list'];
    put?: never;
    /** A new scenario for one of the project's decisions (editors and owners). */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/test-scenarios/{scenario_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One scenario (any member). */
    get: operations['get'];
    /** Changes a scenario (editors and owners). Results already recorded keep it as it ran. */
    put: operations['update'];
    post?: never;
    /** Deletes a scenario (editors and owners). Results already recorded stay. */
    delete: operations['delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness: the service can handle requests that need the database. */
    get: operations['ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/simulate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['simulate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every Studio account, by email (administrators only). */
    get: operations['list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invites a person by email (administrators only). Inviting someone who has not
     *     accepted yet sends a new link and revokes the previous one.
     */
    post: operations['invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The version of Studio that is running. Needs no session, like health. */
    get: operations['version'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccountListResponse: {
      items: components['schemas']['AccountResponse'][];
      /**
       * Format: int64
       * @description Accounts across all pages.
       */
      total: number;
    };
    AccountResponse: {
      /** @description False while the invitation is pending (no password chosen yet). */
      active: boolean;
      /** Format: date-time */
      createdAt: string;
      email: string;
      /** Format: uuid */
      id: string;
      isAdmin: boolean;
      locale: components['schemas']['Locale'];
    };
    /**
     * @description Every kind of state change. The stored text is part of the audit record:
     *     never rename a value, only add new ones.
     * @enum {string}
     */
    Action:
      | 'user.signed_in'
      | 'user.sign_in_failed'
      | 'user.signed_out'
      | 'user.password_set'
      | 'user.password_reset_requested'
      | 'user.invited'
      | 'project.created'
      | 'project.updated'
      | 'project.archived'
      | 'project.restored'
      | 'member.added'
      | 'member.role_changed'
      | 'member.removed'
      | 'decision.created'
      | 'decision.deleted'
      | 'decision.version_saved'
      | 'decision.version_restored'
      | 'scenario.created'
      | 'scenario.updated'
      | 'scenario.deleted';
    AddMemberRequest: {
      /** @description Email of an existing Studio account. */
      email: string;
      role: components['schemas']['Role'];
    };
    AuditEventResponse: {
      action: components['schemas']['Action'];
      actor?: null | components['schemas']['PersonRef'];
      /** @description What changed, e.g. `{ "from": "viewer", "to": "editor" }`. */
      details: unknown;
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      occurredAt: string;
      target?: null | components['schemas']['PersonRef'];
    };
    AuditListResponse: {
      items: components['schemas']['AuditEventResponse'][];
      /**
       * Format: int64
       * @description Events matching the filter, across all pages.
       */
      total: number;
    };
    ChangeRoleRequest: {
      role: components['schemas']['Role'];
    };
    CreateDecisionRequest: {
      /** @description A JDM decision graph. */
      content?: {
        [key: string]: unknown;
      };
      /** @description Lowercase words with single hyphens; folders separated by `/`. */
      key: string;
    };
    CreateProjectRequest: {
      description?: string;
      key: string;
      name: string;
    };
    CreateScenarioRequest: {
      /**
       * Format: uuid
       * @description The decision the scenario evaluates.
       */
      decisionId: string;
      /** @description A JSON object. */
      expected: {
        [key: string]: unknown;
      };
      /** @description A JSON object. */
      input: {
        [key: string]: unknown;
      };
      match: components['schemas']['MatchMode'];
      /** @description Unique among the decision's scenarios (any case). */
      name: string;
    };
    DecisionListResponse: {
      items: components['schemas']['DecisionSummaryResponse'][];
    };
    DecisionResponse: components['schemas']['DecisionSummaryResponse'] & {
      /** @description A JDM decision graph. */
      content: {
        [key: string]: unknown;
      };
    };
    DecisionSummaryResponse: {
      /** @description Whether the draft has changed since that version (true before the first). */
      changedSinceVersion: boolean;
      /** Format: uuid */
      id: string;
      /** @description How graphs call this decision, e.g. `bureau/normalize`. */
      key: string;
      /**
       * Format: int32
       * @description The number of its latest version; absent before the first "Save version".
       */
      latestVersion?: number | null;
      /**
       * Format: int32
       * @description Grows by one on every save; send it back when saving.
       */
      revision: number;
      /** Format: date-time */
      updatedAt: string;
      updatedBy: components['schemas']['PersonRef'];
    };
    DecisionVersionDetailResponse: components['schemas']['DecisionVersionResponse'] & {
      /** @description A JDM decision graph. */
      content: {
        [key: string]: unknown;
      };
    };
    DecisionVersionListResponse: {
      items: components['schemas']['DecisionVersionResponse'][];
      /**
       * Format: int64
       * @description Versions of the decision, across all pages.
       */
      total: number;
    };
    DecisionVersionResponse: {
      /** Format: date-time */
      createdAt: string;
      createdBy: components['schemas']['PersonRef'];
      message: string;
      /**
       * Format: int32
       * @description 1, 2, 3… per decision.
       */
      number: number;
      /**
       * Format: int32
       * @description The older version this one restores, when it does.
       */
      restoredFrom?: number | null;
      /** @description How the project's test scenarios went when this version was saved. */
      tests: components['schemas']['TestSummaryResponse'];
    };
    ErrorBody: {
      /** @description Stable, machine-readable code, e.g. `DECISION_NOT_FOUND`. */
      code: string;
      /** @description Engine error document (failing node and reason) for evaluation failures. */
      details?: unknown;
      fields?: {
        [key: string]: string;
      } | null;
      /** @description Safe to show to a person. */
      message: string;
      /** @description Same value as the `x-request-id` response header; quote it when reporting a problem. */
      requestId: string;
    };
    InvitationRequest: {
      email: string;
      isAdmin?: boolean;
      locale?: null | components['schemas']['Locale'];
    };
    /**
     * @description Language of a user's emails and screens.
     * @enum {string}
     */
    Locale: 'en' | 'fr';
    /**
     * @description How much of the output a scenario pins down.
     * @enum {string}
     */
    MatchMode: 'exact' | 'partial';
    MemberListResponse: {
      items: components['schemas']['MemberResponse'][];
    };
    MemberResponse: {
      /** Format: date-time */
      addedAt: string;
      email: string;
      role: components['schemas']['Role'];
      /** Format: uuid */
      userId: string;
    };
    /**
     * @description One field where the output differs: `path` is dotted (`decision.limit`),
     *     empty for the whole output; a side is absent when the field is missing there.
     */
    MismatchResponse: {
      actual?: unknown;
      expected?: unknown;
      path: string;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordSetupRequest: {
      password: string;
      /** @description The token from the password-setup link. */
      token: string;
    };
    PersonRef: {
      email: string;
      /** Format: uuid */
      id: string;
    };
    ProjectListResponse: {
      items: components['schemas']['ProjectSummaryResponse'][];
      /**
       * Format: int64
       * @description Projects matching the filter, across all pages.
       */
      total: number;
    };
    ProjectResponse: {
      /**
       * Format: date-time
       * @description Set when the project is archived (read-only).
       */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      description: string;
      /** Format: uuid */
      id: string;
      /** @description Immutable, URL-safe identifier. */
      key: string;
      name: string;
      /** @description The reader's role in the project. */
      role: components['schemas']['Role'];
    };
    ProjectSummaryResponse: {
      /** Format: date-time */
      archivedAt?: string | null;
      description: string;
      /** Format: uuid */
      id: string;
      key: string;
      name: string;
      role: components['schemas']['Role'];
    };
    RestoreRequest: {
      /**
       * Format: int32
       * @description The draft revision the editor shows; `409 DECISION_CONFLICT` when it moved on.
       */
      revision: number;
    };
    RestoreResponse: {
      /** @description The decision, its draft now the restored content. */
      decision: components['schemas']['DecisionResponse'];
      /** @description The new version the restore created. */
      version: components['schemas']['DecisionVersionResponse'];
    };
    /**
     * @description What a member may do in a project. Each role includes the ones below it;
     *     variants are declared from least to most, so `Ord` follows that order.
     * @enum {string}
     */
    Role: 'viewer' | 'editor' | 'owner';
    SaveDecisionRequest: {
      /** @description A JDM decision graph. */
      content: {
        [key: string]: unknown;
      };
      /**
       * Format: int32
       * @description The revision this draft was loaded or last saved at.
       */
      revision: number;
    };
    SaveVersionRequest: {
      /** @description What changed and why, for the history. */
      message: string;
      /**
       * Format: int32
       * @description The draft revision the editor shows: the version is exactly that draft.
       */
      revision: number;
    };
    ScenarioListResponse: {
      items: components['schemas']['ScenarioResponse'][];
      /**
       * Format: int64
       * @description Scenarios across all pages.
       */
      total: number;
    };
    ScenarioResponse: {
      /** Format: date-time */
      createdAt: string;
      createdBy: components['schemas']['PersonRef'];
      /** Format: uuid */
      decisionId: string;
      decisionKey: string;
      /** @description A JSON object. */
      expected: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      id: string;
      /** @description A JSON object. */
      input: {
        [key: string]: unknown;
      };
      match: components['schemas']['MatchMode'];
      name: string;
      /** Format: date-time */
      updatedAt: string;
      updatedBy: components['schemas']['PersonRef'];
    };
    SignInRequest: {
      email: string;
      password: string;
    };
    SimulateDecisionRequest: {
      /** @description A JDM decision graph. */
      content?: {
        [key: string]: unknown;
      };
      /** @description Input passed to the decision. */
      context?: Record<string, never>;
    };
    /**
     * @description Design-time evaluation from the editor. The editor sends the whole draft
     *     project so sub-decision references resolve exactly as they will in a release.
     */
    SimulateRequest: {
      /** @description Input passed to the decision. */
      context?: Record<string, never>;
      /** @description Every decision of the project (JDM documents), keyed as graphs reference them. */
      decisions: Record<string, never>;
      /** @description The decision to evaluate. */
      key: string;
    };
    SimulateResponse: {
      /** @description Engine evaluation time, e.g. `412.5µs`. */
      performance: string;
      result: Record<string, never>;
      /** @description Per-node trace: inputs, outputs and timing of each node. */
      trace: Record<string, never>;
    };
    TestResultListResponse: {
      items: components['schemas']['TestResultResponse'][];
      summary: components['schemas']['TestSummaryResponse'];
    };
    /** @description A scenario as it ran on the version, and what happened. */
    TestResultResponse: {
      /** @description What the decision returned; absent when it could not run. */
      actual?: unknown;
      decisionKey: string;
      /** @description It could not run: the engine's message. */
      error?: string | null;
      /** @description A JSON object. */
      expected: {
        [key: string]: unknown;
      };
      /** @description A JSON object. */
      input: {
        [key: string]: unknown;
      };
      match: components['schemas']['MatchMode'];
      /** @description Empty when it passed. */
      mismatches: components['schemas']['MismatchResponse'][];
      /** @description It could not run because this decision has no saved version. */
      missingDecision?: string | null;
      name: string;
      /** Format: uuid */
      scenarioId: string;
      status: components['schemas']['TestStatusResponse'];
    };
    /** @enum {string} */
    TestStatusResponse: 'passed' | 'failed' | 'error';
    /** @description How the project's scenarios went on a version. */
    TestSummaryResponse: {
      /**
       * Format: int64
       * @description Scenarios that could not run (a decision without a version, an evaluation error).
       */
      errors: number;
      /** Format: int64 */
      failed: number;
      /** Format: int64 */
      passed: number;
    };
    UpdateProjectRequest: {
      description?: string;
      name: string;
    };
    UpdateScenarioRequest: {
      /** @description A JSON object. */
      expected: {
        [key: string]: unknown;
      };
      /** @description A JSON object. */
      input: {
        [key: string]: unknown;
      };
      match: components['schemas']['MatchMode'];
      /** @description Unique among the decision's scenarios (any case). */
      name: string;
    };
    UserResponse: {
      email: string;
      /** Format: uuid */
      id: string;
      isAdmin: boolean;
      locale: components['schemas']['Locale'];
    };
    VersionResponse: {
      /**
       * @description Release version baked in at build time, or `unknown` for a local build.
       * @example 1.4.0
       */
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description If the address has an account, a reset link is on its way */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not an email address (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_setup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordSetupRequest'];
      };
    };
    responses: {
      /** @description Password set; sign in with it */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Link invalid, used or expired (INVALID_SETUP_LINK), or password too short or too long (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_in: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest'];
      };
    };
    responses: {
      /** @description Signed in; the session cookie is set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Email or password is incorrect, or the account is locked (INVALID_CREDENTIALS) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Missing CSRF header (CSRF_REQUIRED) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_out: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The service is running */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ok */
          'text/plain': string;
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description `true` lists archived projects instead of active ones. */
        archived?: boolean;
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectListResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Invalid key, name or description (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Key already used (PROJECT_KEY_TAKEN) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_by_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's key, e.g. `credit-pme`. */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description No such project, or not a member (PROJECT_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description No such project, or not a member (PROJECT_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProjectRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Invalid name or description (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Only events by this person. */
        actor?: string;
        /** @description Only this kind of change. */
        action?: components['schemas']['Action'];
        /** @description From this instant, inclusive (ISO-8601). */
        from?: string;
        /** @description Until this instant, exclusive (ISO-8601). */
        until?: string;
        /** @description Page size, 1 to 100 (default 50). Ignored by the export. */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditListResponse'];
        };
      };
      /** @description Invalid filter (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  export: {
    parameters: {
      query?: {
        /** @description Only events by this person. */
        actor?: string;
        /** @description Only this kind of change. */
        action?: components['schemas']['Action'];
        /** @description From this instant, inclusive (ISO-8601). */
        from?: string;
        /** @description Until this instant, exclusive (ISO-8601). */
        until?: string;
        /** @description Page size, 1 to 100 (default 50). Ignored by the export. */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV: occurred_at, actor, action, target, details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDecisionRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionResponse'];
        };
      };
      /** @description Invalid key (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Viewers cannot create decisions (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description DECISION_KEY_TAKEN or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description The content is not a decision model (INVALID_DECISION) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  save: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveDecisionRequest'];
      };
    };
    responses: {
      /** @description Saved; the new revision */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionSummaryResponse'];
        };
      };
      /** @description Viewers cannot save (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description DECISION_CONFLICT (details: revision, updatedAt, updatedBy) or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description The content is not a decision model (INVALID_DECISION) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Viewers cannot delete (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  simulate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SimulateDecisionRequest'];
      };
    };
    responses: {
      /** @description Result and per-node trace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimulateResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description A decision of the project is not a valid model (INVALID_DECISION), or the evaluation failed (EVALUATION_FAILED, trace in details) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionVersionListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  save: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveVersionRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionVersionResponse'];
        };
      };
      /** @description Missing or too long message (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Viewers cannot save versions (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description DECISION_CONFLICT (the draft moved on) or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Nothing changed since the latest version (VERSION_UNCHANGED, details: version) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DecisionVersionDetailResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND, DECISION_NOT_FOUND or VERSION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestoreRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestoreResponse'];
        };
      };
      /** @description Viewers cannot restore (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND, DECISION_NOT_FOUND or VERSION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description DECISION_CONFLICT (the draft moved on) or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  test_results: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        decision_id: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestResultListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND, DECISION_NOT_FOUND or VERSION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  add_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Already a member (ALREADY_MEMBER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description No account with this email (NO_SUCH_USER) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or MEMBER_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Last owner (LAST_OWNER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  change_role: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeRoleRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or MEMBER_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Last owner (LAST_OWNER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Only the scenarios of this decision. */
        decisionId?: string;
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateScenarioRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioResponse'];
        };
      };
      /** @description Invalid name, input or expected output (INVALID_REQUEST, fields) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Viewers cannot change scenarios (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or DECISION_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description SCENARIO_NAME_TAKEN or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND or SCENARIO_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateScenarioRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioResponse'];
        };
      };
      /** @description Invalid name, input or expected output (INVALID_REQUEST, fields) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Viewers cannot change scenarios (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or SCENARIO_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description SCENARIO_NAME_TAKEN or PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Viewers cannot change scenarios (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or SCENARIO_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_ARCHIVED */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ready */
          'text/plain': string;
        };
      };
      /** @description The database is not reachable (DATABASE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  simulate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SimulateRequest'];
      };
    };
    responses: {
      /** @description Result and per-node trace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimulateResponse'];
        };
      };
      /** @description Malformed request body (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description No decision with that key (DECISION_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Invalid decision model (INVALID_DECISION) or evaluation error (EVALUATION_FAILED) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountListResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationRequest'];
      };
    };
    responses: {
      /** @description Account created; the invitation email is on its way */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid email (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description The person already has an account (EMAIL_TAKEN) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
}
