/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user. */
    get: operations['me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emails a one-time link to choose a new password. Answers the same whether or
     *     not the address has an account, so it cannot be used to find accounts.
     */
    post: operations['password_reset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password-setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sets a password from a one-time setup link. Ends the user's other sessions. */
    post: operations['password_setup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in and sets the httpOnly session cookie. */
    post: operations['sign_in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session on the server and clears the cookie. */
    post: operations['sign_out'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness: answers as long as the process serves requests. Does not touch the database. */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects the signed-in user is a member of, by name. */
    get: operations['list'];
    put?: never;
    /** Creates a project (administrators only). The creator becomes its owner. */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A project the signed-in user is a member of. */
    get: operations['get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Renames the project or changes its description (owners). The key never changes. */
    patch: operations['update'];
    trace?: never;
  };
  '/projects/{project_id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archives the project: read-only and hidden from the default list (owners). */
    post: operations['archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The project's audit log, newest first (owners). */
    get: operations['list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/audit/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The project's audit log as CSV, with the same filters (owners). At most
     *     50,000 rows; narrow the dates for more.
     */
    get: operations['export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Members of the project, owners first, then by email (any member). */
    get: operations['members'];
    put?: never;
    /** Adds an existing Studio user to the project (owners). */
    post: operations['add_member'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{project_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Removes a member; the last owner cannot be removed (owners). */
    delete: operations['remove_member'];
    options?: never;
    head?: never;
    /** Changes a member's role; a project always keeps an owner (owners). */
    patch: operations['change_role'];
    trace?: never;
  };
  '/projects/{project_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restores an archived project (owners). */
    post: operations['restore'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness: the service can handle requests that need the database. */
    get: operations['ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/simulate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['simulate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every Studio account, by email (administrators only). */
    get: operations['list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invites a person by email (administrators only). Inviting someone who has not
     *     accepted yet sends a new link and revokes the previous one.
     */
    post: operations['invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The version of Studio that is running. Needs no session, like health. */
    get: operations['version'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccountListResponse: {
      items: components['schemas']['AccountResponse'][];
      /**
       * Format: int64
       * @description Accounts across all pages.
       */
      total: number;
    };
    AccountResponse: {
      /** @description False while the invitation is pending (no password chosen yet). */
      active: boolean;
      /** Format: date-time */
      createdAt: string;
      email: string;
      /** Format: uuid */
      id: string;
      isAdmin: boolean;
      locale: components['schemas']['Locale'];
    };
    /**
     * @description Every kind of state change. The stored text is part of the audit record:
     *     never rename a value, only add new ones.
     * @enum {string}
     */
    Action:
      | 'user.signed_in'
      | 'user.sign_in_failed'
      | 'user.signed_out'
      | 'user.password_set'
      | 'user.password_reset_requested'
      | 'user.invited'
      | 'project.created'
      | 'project.updated'
      | 'project.archived'
      | 'project.restored'
      | 'member.added'
      | 'member.role_changed'
      | 'member.removed';
    AddMemberRequest: {
      /** @description Email of an existing Studio account. */
      email: string;
      role: components['schemas']['Role'];
    };
    AuditEventResponse: {
      action: components['schemas']['Action'];
      actor?: null | components['schemas']['PersonRef'];
      /** @description What changed, e.g. `{ "from": "viewer", "to": "editor" }`. */
      details: unknown;
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      occurredAt: string;
      target?: null | components['schemas']['PersonRef'];
    };
    AuditListResponse: {
      items: components['schemas']['AuditEventResponse'][];
      /**
       * Format: int64
       * @description Events matching the filter, across all pages.
       */
      total: number;
    };
    ChangeRoleRequest: {
      role: components['schemas']['Role'];
    };
    CreateProjectRequest: {
      description?: string;
      key: string;
      name: string;
    };
    ErrorBody: {
      /** @description Stable, machine-readable code, e.g. `DECISION_NOT_FOUND`. */
      code: string;
      /** @description Engine error document (failing node and reason) for evaluation failures. */
      details?: unknown;
      fields?: {
        [key: string]: string;
      } | null;
      /** @description Safe to show to a person. */
      message: string;
      /** @description Same value as the `x-request-id` response header; quote it when reporting a problem. */
      requestId: string;
    };
    InvitationRequest: {
      email: string;
      isAdmin?: boolean;
      locale?: null | components['schemas']['Locale'];
    };
    /**
     * @description Language of a user's emails and screens.
     * @enum {string}
     */
    Locale: 'en' | 'fr';
    MemberListResponse: {
      items: components['schemas']['MemberResponse'][];
    };
    MemberResponse: {
      /** Format: date-time */
      addedAt: string;
      email: string;
      role: components['schemas']['Role'];
      /** Format: uuid */
      userId: string;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordSetupRequest: {
      password: string;
      /** @description The token from the password-setup link. */
      token: string;
    };
    PersonRef: {
      email: string;
      /** Format: uuid */
      id: string;
    };
    ProjectListResponse: {
      items: components['schemas']['ProjectSummaryResponse'][];
      /**
       * Format: int64
       * @description Projects matching the filter, across all pages.
       */
      total: number;
    };
    ProjectResponse: {
      /**
       * Format: date-time
       * @description Set when the project is archived (read-only).
       */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      description: string;
      /** Format: uuid */
      id: string;
      /** @description Immutable, URL-safe identifier. */
      key: string;
      name: string;
      /** @description The reader's role in the project. */
      role: components['schemas']['Role'];
    };
    ProjectSummaryResponse: {
      /** Format: date-time */
      archivedAt?: string | null;
      description: string;
      /** Format: uuid */
      id: string;
      key: string;
      name: string;
      role: components['schemas']['Role'];
    };
    /**
     * @description What a member may do in a project. Each role includes the ones below it;
     *     variants are declared from least to most, so `Ord` follows that order.
     * @enum {string}
     */
    Role: 'viewer' | 'editor' | 'owner';
    SignInRequest: {
      email: string;
      password: string;
    };
    /**
     * @description Design-time evaluation from the editor. The editor sends the whole draft
     *     project so sub-decision references resolve exactly as they will in a release.
     */
    SimulateRequest: {
      /** @description Input passed to the decision. */
      context?: Record<string, never>;
      /** @description Every decision of the project (JDM documents), keyed as graphs reference them. */
      decisions: Record<string, never>;
      /** @description The decision to evaluate. */
      key: string;
    };
    SimulateResponse: {
      /** @description Engine evaluation time, e.g. `412.5µs`. */
      performance: string;
      result: Record<string, never>;
      /** @description Per-node trace: inputs, outputs and timing of each node. */
      trace: Record<string, never>;
    };
    UpdateProjectRequest: {
      description?: string;
      name: string;
    };
    UserResponse: {
      email: string;
      /** Format: uuid */
      id: string;
      isAdmin: boolean;
      locale: components['schemas']['Locale'];
    };
    VersionResponse: {
      /**
       * @description Release version baked in at build time, or `unknown` for a local build.
       * @example 1.4.0
       */
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description If the address has an account, a reset link is on its way */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not an email address (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  password_setup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordSetupRequest'];
      };
    };
    responses: {
      /** @description Password set; sign in with it */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Link invalid, used or expired (INVALID_SETUP_LINK), or password too short or too long (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_in: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest'];
      };
    };
    responses: {
      /** @description Signed in; the session cookie is set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Email or password is incorrect, or the account is locked (INVALID_CREDENTIALS) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Missing CSRF header (CSRF_REQUIRED) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  sign_out: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The service is running */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ok */
          'text/plain': string;
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description `true` lists archived projects instead of active ones. */
        archived?: boolean;
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectListResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Invalid key, name or description (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Key already used (PROJECT_KEY_TAKEN) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description No such project, or not a member (PROJECT_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProjectRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Invalid name or description (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Only events by this person. */
        actor?: string;
        /** @description Only this kind of change. */
        action?: components['schemas']['Action'];
        /** @description From this instant, inclusive (ISO-8601). */
        from?: string;
        /** @description Until this instant, exclusive (ISO-8601). */
        until?: string;
        /** @description Page size, 1 to 100 (default 50). Ignored by the export. */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditListResponse'];
        };
      };
      /** @description Invalid filter (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  export: {
    parameters: {
      query?: {
        /** @description Only events by this person. */
        actor?: string;
        /** @description Only this kind of change. */
        action?: components['schemas']['Action'];
        /** @description From this instant, inclusive (ISO-8601). */
        from?: string;
        /** @description Until this instant, exclusive (ISO-8601). */
        until?: string;
        /** @description Page size, 1 to 100 (default 50). Ignored by the export. */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV: occurred_at, actor, action, target, details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberListResponse'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  add_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Already a member (ALREADY_MEMBER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description No account with this email (NO_SUCH_USER) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or MEMBER_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Last owner (LAST_OWNER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  change_role: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeRoleRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND or MEMBER_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Last owner (LAST_OWNER) or archived (PROJECT_ARCHIVED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Not an owner (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description PROJECT_NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example ready */
          'text/plain': string;
        };
      };
      /** @description The database is not reachable (DATABASE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  simulate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SimulateRequest'];
      };
    };
    responses: {
      /** @description Result and per-node trace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimulateResponse'];
        };
      };
      /** @description Malformed request body (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description No decision with that key (DECISION_NOT_FOUND) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Invalid decision model (INVALID_DECISION) or evaluation error (EVALUATION_FAILED) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        /** @description Page size, 1 to 100 (default 50). */
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountListResponse'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationRequest'];
      };
    };
    responses: {
      /** @description Account created; the invitation email is on its way */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid email (INVALID_REQUEST) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not signed in (UNAUTHENTICATED) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Not an administrator (FORBIDDEN) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description The person already has an account (EMAIL_TAKEN) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
}
